#!/usr/bin/env bash
set -euo pipefail

# setup-claude-integration.sh - Set up Claude Code skill discovery
#
# Creates symlinks from .claude/skills/ to .agents/skills/ so that
# dot-agents skills appear in Claude Code's native / menu.
# Called by sync scripts after syncing, or run standalone.

# Colors (only if terminal supports them)
if [[ -t 1 ]]; then
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    RED='\033[0;31m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    GREEN='' YELLOW='' RED='' BLUE='' NC=''
fi

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[✓]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

usage() {
    cat <<EOF
Usage: setup-claude-integration.sh [OPTIONS]

Set up Claude Code skill discovery via .claude/skills/ symlinks.

This ensures that:
  - .claude/skills/ symlinks are created for skill discovery
  - .claude/skills/.gitignore is properly configured
  - Stale symlinks are cleaned up

Options:
  --dry-run    Show what would be changed without making changes
  --quiet      Suppress informational output (errors still shown)
  --help       Show this help message

Examples:
  # Set up Claude Code integration
  .agents/scripts/setup-claude-integration.sh

  # Preview changes first
  .agents/scripts/setup-claude-integration.sh --dry-run
EOF
}

DRY_RUN=false
QUIET=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --quiet)
            QUIET=true
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Paths
agents_skills_dir=".agents/skills"
claude_skills_dir=".claude/skills"

# Auto-detect: only integrate if .claude/ directory exists
if [[ ! -d ".claude" ]]; then
    if [[ "$QUIET" != "true" ]]; then
        log_warn "No .claude/ directory found — skipping Claude Code integration"
    fi
    exit 0
fi

if [[ "$QUIET" != "true" ]]; then
    log_info "Setting up Claude Code skill discovery..."
fi

# Build gitignore content
gitignore_content="# Auto-generated by dot-agents — do not edit manually"
gitignore_content="${gitignore_content}\n# Symlinks to .agents/skills/ for native Claude Code discovery"
gitignore_content="${gitignore_content}\n# See: https://dot-agents.dev"

linked=0

# Create symlinks for each skill
if [[ -d "$agents_skills_dir" ]]; then
    for skill_dir in "$agents_skills_dir"/*/; do
        [[ -d "$skill_dir" ]] || continue
        skill_name="$(basename "$skill_dir")"
        skill_md="$skill_dir/SKILL.md"

        # Skip if no SKILL.md
        [[ -f "$skill_md" ]] || continue

        target_dir="$claude_skills_dir/$skill_name"
        target_file="$target_dir/SKILL.md"

        # Skip if a non-symlink file already exists (user-created skill)
        if [[ -f "$target_file" ]] && [[ ! -L "$target_file" ]]; then
            log_warn "Skipping $target_file (not a symlink — user-created skill?)"
            continue
        fi

        if [[ "$DRY_RUN" == "true" ]]; then
            log_info "Would create: $target_file"
        else
            mkdir -p "$target_dir"
            relative_path="../../../.agents/skills/$skill_name/SKILL.md"

            if ln -sf "$relative_path" "$target_file" 2>/dev/null; then
                log_success "Linked $claude_skills_dir/$skill_name/SKILL.md"
            else
                # Fallback: copy if symlinks not supported
                cp "$skill_md" "$target_file"
                log_success "Copied $claude_skills_dir/$skill_name/SKILL.md (symlink not supported)"
            fi
        fi
        gitignore_content="${gitignore_content}\n${skill_name}/"
        linked=$((linked + 1))
    done
fi

# Clean up stale symlinks (skills removed upstream)
if [[ -d "$claude_skills_dir" ]]; then
    for target_dir in "$claude_skills_dir"/*/; do
        [[ -d "$target_dir" ]] || continue
        skill_name="$(basename "$target_dir")"
        target_file="$target_dir/SKILL.md"

        # Only clean up symlinks we created (not user files)
        if [[ -L "$target_file" ]] && [[ ! -d "$agents_skills_dir/$skill_name" ]]; then
            if [[ "$DRY_RUN" == "true" ]]; then
                log_info "Would remove: $target_file (stale symlink)"
            else
                rm -f "$target_file"
                rmdir "$target_dir" 2>/dev/null || true
                log_warn "Removed stale $claude_skills_dir/$skill_name/ symlink"
            fi
        fi
    done
fi

# Write gitignore for dot-agents skill symlinks
if [[ "$DRY_RUN" == "true" ]]; then
    log_info "Would update: $claude_skills_dir/.gitignore"
else
    mkdir -p "$claude_skills_dir"
    echo -e "$gitignore_content" > "$claude_skills_dir/.gitignore"
fi

if [[ "$QUIET" != "true" ]]; then
    echo ""
    if [[ $linked -gt 0 ]]; then
        log_success "Claude Code integration complete — $linked skill(s) available in / menu"
    else
        log_warn "No skills found to link"
    fi

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "Run without --dry-run to apply changes"
    fi
fi
